# Note the values in this file are currently (2020-06-20) the default values
# that would be already assumed by codecov if the file was not present.
# Nevertheless, the inclusion of the file makes the behaviour more explicit
# to future software maintainers.
codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "75...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false